title: tituy
author: tepythai
email: thaitepy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 hehe :smile:

# social links
twitter_username: tepythai
github_username:  tepythai

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
