title: TepyThai
author: tepythai
email: thaitepy@gmail.com
description: > # this means lines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: tepythau
github_username:  tepythai

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
